#!/command/with-contenv bash
# shellcheck shell=bash

set -e

. /usr/bin/common.sh

log_info 'Starting nginx ...'
while true; do
	if nginx -t -g "error_log off;" >/tmp/nginx-test.log 2>&1; then
		exec s6-setuidgid "$PUID:$PGID" nginx
	fi
	log_error "Nginx config test failed, retrying in 5s."
	if [ -s /tmp/nginx-test.log ]; then
		while IFS= read -r line; do
			log_error "$line"
		done < /tmp/nginx-test.log
	fi
	bad_file=$(awk '{ for (i=1; i<=NF; i++) { if ($i ~ /^\/data\/nginx\/.*\.conf:[0-9]+$/) { sub(/:[0-9]+$/, "", $i); print $i; exit } } }' /tmp/nginx-test.log)
	if [ -n "$bad_file" ] && [ -f "$bad_file" ]; then
		log_error "Quarantining bad config: $bad_file"
		mv "$bad_file" "${bad_file}.err"
		continue
	fi
	sleep 5
done
