log_format stream '[$time_local] $protocol $status '
	'[Client $remote_addr:$remote_port] '
	'[Server $server_addr:$server_port] '
	'[Bytes $bytes_received/$bytes_sent] '
	'[Session $session_time] '
	'[Upstream $upstream_addr] '
	'[UpstreamBytes $upstream_bytes_received/$upstream_bytes_sent] '
	'[UpstreamTime $upstream_connect_time/$upstream_session_time]';
