name: ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: frontend/yarn.lock
      - name: Frontend lint/test/build
        working-directory: frontend
        env:
          CI: true
          NODE_OPTIONS: --openssl-legacy-provider
        run: |
          corepack enable
          yarn install --frozen-lockfile
          yarn lint
          yarn test:ci
          yarn build
      - name: Docker build
        run: docker buildx build -f docker/Dockerfile --platform linux/amd64 -t nginx-proxy-manager:local --load . --no-cache
