# This file is managed by Nginx Proxy Manager
{% if zones.size == 0 %}
# No rate limits configured
{% else %}
{% for zone in zones %}
limit_req_zone $binary_remote_addr zone={{ zone.name }}:{{ zone.size }} rate={{ zone.rate }}r/s;
{% endfor %}
{% endif %}
